### ISSUE TITLE
Cannot find module './routes/taskResult.route' or its corresponding type declarations

### ISSUE THREAD

**Issue by sammcj** [MarianoMolina/project_alice#1]
Looking at the repo it appears the file is lowercase (taskresult.route.ts) which I suspect might cause the issue.

```
 => ERROR [alice-backend 7/7] RUN npm run build                                                                                                                         2.2s
------
 > [alice-backend 7/7] RUN npm run build:
0.239
0.239 > backend@1.0.0 build
0.239 > tsc
0.239
2.116 src/app.ts(12,30): error TS2307: Cannot find module './routes/taskResult.route' or its corresponding type declarations.
```

```

  &name alice:
    hostname: *name
    container_name: *name
    <<: [*ai-common, *restart, *secopts]
    profiles:
      - alice
    build:
      context:  https://github.com/MarianoMolina/project_alice.git#main:alice_frontend/
      dockerfile: Dockerfile
    ports:
      - 3000 
    links:
      - alice-mongo
      - alice-backend
      - alice-workflow
      - ollama
    depends_on:
      alice-backend:
        condition: service_healthy
      alice-workflow:
        condition: service_healthy
    volumes:
      # - ./alice_frontend:/app:delegated
      - /mnt/llm/alice/node_modules:/app/node_modules
    env_file:
      - ./env/.alice.env
    networks:
      - traefik-servicenet
    labels:
      traefik.enable: true
      org.hotio.pullio.update: true
      traefik.http.routers.alice.rule: Host(`alice.my.internal.domain`)
      traefik.http.routers.alice.tls.certresolver: le
      traefik.http.routers.alice.entrypoints: websecure
      traefik.http.routers.alice.tls.domains[0].main: "*.my.internal.domain"
      traefik.http.routers.alice.service: alice-service
      traefik.http.services.alice-service.loadbalancer.server.port: 3000
      traefik.http.routers.alice.middlewares: authentik

  &name alice-backend:
    hostname: *name
    container_name: *name
    <<: [*ai-common, *restart, *secopts]
    profiles:
      - alice
    build:
      context: https://github.com/MarianoMolina/project_alice.git#main:backend/
      dockerfile: Dockerfile
    ports:
      - 3000
    depends_on:
      alice-mongo:
        condition: service_started
    volumes:
      - ./env/.alice.env:/app/.env
      # - /mnt/llm/alice/app:/app
      - /mnt/llm/alice/node_modules:/app/node_module
    command: sh -c "npm run build && nodemon --watch src --ext ts --exec 'npm run build && node dist/index.js'"
    env_file:
      - ./env/.alice.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - traefik-servicenet
    labels:
      traefik.enable: true
      org.hotio.pullio.update: true
      traefik.http.routers.alice-backend.rule: Host(`alice-backend.my.internal.domain`)
      traefik.http.routers.alice-backend.tls.certresolver: le
      traefik.http.routers.alice-backend.entrypoints: websecure
      traefik.http.routers.alice-backend.tls.domains[0].main: "*.my.internal.domain"
      traefik.http.routers.alice-backend.service: alice-backend-service
      traefik.http.services.alice-backend-service.loadbalancer.server.port: 3000
      # traefik.http.routers.alice-backend.middlewares: authentik

  &name alice-mongo:
    hostname: *name
    container_name: *name
    <<: [*ai-common, *restart, *secopts]
    profiles:
      - alice
    image: mongo:latest
    ports:
      - 26017
    volumes:
      - /mnt/llm/alice/mongo_data:/data/db
    env_file:
      - ./env/.alice.env
    networks:
      - traefik-servicenet
    labels:
      traefik.enable: false
      org.hotio.pullio.update: true

  &name alice-workflow:
    hostname: *name
    container_name: *name
    <<: [*ai-common, *restart, *secopts]
    profiles:
      - alice
    build:
      context: https://github.com/MarianoMolina/project_alice.git#main:workflow_logic/
    ports:
      - 8000
    volumes:
      # - /mnt/llm/alice/app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      alice-backend:
        condition: service_healthy
    env_file:
      - ./env/.alice.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    networks:
      - traefik-servicenet
    labels:
      traefik.enable: true
      org.hotio.pullio.update: true
      traefik.http.routers.alice-workflow.rule: Host(`alice-workflow.my.internal.domain`)
      traefik.http.routers.alice-workflow.tls.certresolver: le
      traefik.http.routers.alice-workflow.entrypoints: websecure
      traefik.http.routers.alice-workflow.tls.domains[0].main: "*.my.internal.domain"
      traefik.http.routers.alice-workflow.service: alice-workflow-service
      traefik.http.services.alice-workflow-service.loadbalancer.server.port: 8000
      # traefik.http.routers.alice-workflow.middlewares: authentik
```
